changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - github-actions[bot]
      - dependabot[bot]
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
        - Semver-Major
    - title: Features
      labels:
        - enhancement
        - feature
        - Semver-Minor
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Maintenance
      labels:
        - chore
        - dependencies
        - refactor
    - title: Other Changes
      labels:
        - "*"
