import { contextBridge, ipcRenderer } from "electron";

contextBridge.exposeInMainWorld("arcforge", {
  chooseWorkspace: () => ipcRenderer.invoke("workspace:choose"),
  chooseDirectory: (defaultPath?: string, parentPath?: string) => ipcRenderer.invoke("workspace:chooseDirectory", defaultPath, parentPath),
  scanWorkspace: (root: string) => ipcRenderer.invoke("workspace:scan", root),
  auditWorkspace: (root: string, options?: unknown) => ipcRenderer.invoke("workspace:audit", root, options),
  saveConfig: (root: string, config: unknown) => ipcRenderer.invoke("workspace:saveConfig", root, config),
  openWorkspaceFolder: (root: string) => ipcRenderer.invoke("workspace:openFolder", root),
  getDefaultTargets: () => ipcRenderer.invoke("system:defaultTargets"),
  scanInstalledSkills: (options?: unknown) => ipcRenderer.invoke("installed:scan", options),
  createInstalledSkillOrganizePlan: (options?: unknown) => ipcRenderer.invoke("installed:organizePlan", options),
  organizeInstalledSkills: (options?: unknown, confirm?: boolean) => ipcRenderer.invoke("installed:organizeRun", options, confirm),
  getEnvironmentStatus: () => ipcRenderer.invoke("system:environment"),
  installCli: () => ipcRenderer.invoke("system:installCli"),
  openExternal: (url: string) => ipcRenderer.invoke("system:openExternal", url),
  loadAppState: () => ipcRenderer.invoke("appState:load"),
  saveAppState: (patch: unknown) => ipcRenderer.invoke("appState:save", patch),
  migrateAppState: (legacyState: unknown, origin: string) => ipcRenderer.invoke("appState:migrate", legacyState, origin),
  rememberProjectWorkspace: (workspace: unknown, orderedPaths?: string[]) => ipcRenderer.invoke("projectList:remember", workspace, orderedPaths),
  reorderProjectWorkspaces: (orderedPaths: string[]) => ipcRenderer.invoke("projectList:reorder", orderedPaths),
  removeProjectWorkspace: (root: string) => ipcRenderer.invoke("projectList:remove", root),
  addRemoteWorkspace: (remoteUrl: string) => ipcRenderer.invoke("workspace:addRemote", remoteUrl),
  sourceUpdateStatus: (root: string) => ipcRenderer.invoke("source:status", root),
  updateSource: (root: string, confirm?: boolean) => ipcRenderer.invoke("source:update", root, confirm),
  createMergePlan: (options: unknown) => ipcRenderer.invoke("merge:plan", options),
  mergeIntoProject: (options: unknown) => ipcRenderer.invoke("merge:run", options),
  createImportSkillsPlan: (options: unknown) => ipcRenderer.invoke("import:plan", options),
  importSkillsIntoProject: (options: unknown) => ipcRenderer.invoke("import:run", options),
  listAppliedSources: (root: string) => ipcRenderer.invoke("applied:list", root),
  driftAppliedSources: (root: string, id?: string) => ipcRenderer.invoke("applied:drift", root, id),
  runAppliedSources: (root: string, id?: string, cleanupPaths?: string[]) => ipcRenderer.invoke("applied:run", root, id, cleanupPaths),
  createSkillAvailabilityPlan: (options: unknown) => ipcRenderer.invoke("apply:plan", options),
  applySkillAvailabilityPlan: (options: unknown) => ipcRenderer.invoke("apply:run", options),
  driftSkillAvailability: (options: unknown) => ipcRenderer.invoke("apply:drift", options),
  applyFromSource: (root: string, from: string | undefined, profile: string, targetDir: string, save?: boolean, skills?: string[]) => ipcRenderer.invoke("apply:run", root, from, profile, targetDir, save, skills),
  driftFromSource: (root: string, from: string | undefined, profile: string, targetDir: string, skills?: string[]) => ipcRenderer.invoke("apply:drift", root, from, profile, targetDir, skills),
  createSharePlan: (root: string, remoteUrl: string, visibility: "private" | "public", targetMode: "direct" | "namedProject", projectName: string, profileName: string, message?: string, delivery?: string, branch?: string, sameRepository?: boolean, sameRepositoryRemote?: string, readinessAssessment?: unknown) => ipcRenderer.invoke("share:plan", root, remoteUrl, visibility, targetMode, projectName, profileName, message, delivery, branch, sameRepository, sameRepositoryRemote, readinessAssessment),
  shareProject: (root: string, remoteUrl: string, visibility: "private" | "public", message: string, targetMode: "direct" | "namedProject", projectName: string, profileName: string, delivery?: string, branch?: string, confirm?: boolean, sameRepository?: boolean, sameRepositoryRemote?: string, readinessAssessment?: unknown) => ipcRenderer.invoke("share:run", root, remoteUrl, visibility, message, targetMode, projectName, profileName, delivery, branch, confirm, sameRepository, sameRepositoryRemote, readinessAssessment),
  shareDriftReport: (root: string, remoteUrl: string, targetMode: "direct" | "namedProject", projectName: string, profileName: string, sameRepository?: boolean, sameRepositoryRemote?: string) => ipcRenderer.invoke("share:drift", root, remoteUrl, targetMode, projectName, profileName, sameRepository, sameRepositoryRemote),
  openDriftDiff: (report: unknown) => ipcRenderer.invoke("diff:openDrift", report),
  listSkillFiles: (root: string, skillPath: string) => ipcRenderer.invoke("skillFile:list", root, skillPath),
  listWorkspaceFiles: (root: string, directoryPath: string) => ipcRenderer.invoke("skillFile:listWorkspace", root, directoryPath),
  readSkillFile: (root: string, filePath: string) => ipcRenderer.invoke("skillFile:read", root, filePath),
  writeSkillFile: (root: string, filePath: string, content: string) => ipcRenderer.invoke("skillFile:write", root, filePath, content),
  openSkillFileWindow: (root: string, skillPath: string, filePath?: string, context?: unknown) => ipcRenderer.invoke("skillFile:openWindow", root, skillPath, filePath, context),
  openWorkspaceFileWindow: (root: string, directoryPath: string, filePath?: string, context?: unknown) => ipcRenderer.invoke("skillFile:openWorkspaceWindow", root, directoryPath, filePath, context)
});
