import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { readFile } from "node:fs/promises";
import { test } from "node:test";

test("arcforge install skill defines source install boundaries", async () => {
  const skill = await readFile(new URL("../skills/arcforge-install/SKILL.md", import.meta.url), "utf8");
  const agentYaml = await readFile(new URL("../skills/arcforge-install/agents/openai.yaml", import.meta.url), "utf8");
  const script = await readFile(new URL("../skills/arcforge-install/scripts/install-from-repo.mjs", import.meta.url), "utf8");
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const enReadme = await readFile(new URL("../docs/en/README.md", import.meta.url), "utf8");
  const zhReadme = await readFile(new URL("../docs/zh-CN/README.md", import.meta.url), "utf8");
  const arcforgeDesktopRouting = await readFile(new URL("../skills/arcforge/references/desktop-routing.md", import.meta.url), "utf8");
  const arcforgeCliOrchestration = await readFile(new URL("../skills/arcforge/references/cli-orchestration.md", import.meta.url), "utf8");
  const cliInstall = await readFile(new URL("../src/core/cli-install.ts", import.meta.url), "utf8");

  assert.match(skill, /name: arcforge-install/);
  assert.match(skill, /# ArcForge Install/);
  assert.match(skill, /skills\/arcforge/);
  assert.match(skill, /skills\/arcforge-skill-first/);
  assert.match(skill, /~\/\.codex\/skills\/arcforge/);
  assert.match(skill, /~\/\.codex\/skills\/arcforge-skill-first/);
  assert.match(skill, /arcforge-desktop/);
  assert.match(skill, /--desktop install/);
  assert.match(skill, /--desktop build/);
  assert.match(skill, /--desktop package/);
  assert.match(skill, /--update-path/);
  assert.match(skill, /--home/);
  assert.match(skill, /--shim-dir/);
  assert.match(skill, /--dry-run/);
  assert.match(skill, /--verify/);
  assert.match(skill, /--npm-cache/);
  assert.match(skill, /env PATH="\/private\/tmp\/arcforge-install-home\/\.local\/bin:\$PATH"/);
  assert.match(skill, /临时 shim 目录排在 PATH 最前/);
  assert.match(skill, /真实用户级 `arcforge` 或 `arcforge-desktop` wrapper/);
  assert.match(skill, /临时 HOME 外的不可修复 PATH shadow/);
  assert.match(skill, /--recommended-skills/);
  assert.match(skill, /真实 `~\/\.npm`/);
  assert.match(skill, /https:\/\/github\.com\/feitianchengzi\/arckit/);
  assert.match(skill, /https:\/\/github\.com\/feitianchengzi\/arckit-code/);
  assert.match(skill, /AI Agent Skills 中心/);
  assert.match(skill, /完整协作生命周期/);
  assert.match(skill, /不维护具体技术栈 coding workflow/);
  assert.match(skill, /具体技术栈 coding skills 仓库/);
  assert.match(skill, /SwiftUI\/Apple 客户端默认架构/);
  assert.match(skill, /反馈平台接入流程/);
  assert.match(skill, /用户可以选择快速安装模式、严格治理模式或暂不安装/);
  assert.match(skill, /飞天橙子内部使用者和开源仓库使用者走同一个 GitHub-first 安装路径/);
  assert.match(skill, /--recommended-mode/);
  assert.match(skill, /不要保留旧式隐式快速安装命令/);
  assert.match(skill, /快速安装模式/);
  assert.match(skill, /严格治理模式/);
  assert.match(skill, /pending_install_mode_choice/);
  assert.match(skill, /pending_quick_skill_choice/);
  assert.match(skill, /pending_governance_endpoints/);
  assert.match(skill, /--recommended-skills all/);
  assert.match(skill, /--recommended-skills skip/);
  assert.match(skill, /AGENT ACTION REQUIRED: recommended install mode choice pending/);
  assert.match(skill, /Recommended skill stage: pending_install_mode_choice/);
  assert.match(skill, /最后一个 agent-facing action/);
  assert.match(skill, /最后动作门禁/);
  assert.match(skill, /等待用户选择推荐安装模式/);
  assert.match(skill, /不能只写“推荐 skills 阶段未静默安装”/);
  assert.match(skill, /你希望使用哪种模式/);
  assert.match(skill, /drift --root <arcforge repo> --from <repo url>/);
  assert.match(skill, /apply --root <arcforge repo> --from <repo url>/);
  assert.match(skill, /apply --root <record-or-maintenance-root> --from <repo url>/);
  assert.match(skill, /--save --confirm/);
  assert.match(skill, /Headless 验证/);
  assert.match(skill, /--skip-npm-install/);
  assert.match(skill, /npm run build:cli/);
  assert.match(skill, /写入当前仓库的 `dist\/`/);
  assert.match(skill, /写入 `dist-ui\/`/);
  assert.match(skill, /不要把这个安装流程描述成 marketplace/);
  assert.match(skill, /持久 PATH/);
  assert.match(skill, /agent 注入的临时 PATH/);
  assert.match(skill, /command -v arcforge-desktop/);
  assert.match(skill, /<CLI shim path> doctor/);
  assert.match(skill, /<CLI shim path> scan --root \./);
  assert.match(skill, /当前会话 PATH 噪声/);
  assert.match(skill, /PATH shadow/);
  assert.match(skill, /必须修复可修复的 PATH shadow/);
  assert.match(skill, /首个非临时 `arcforge`/);
  assert.match(skill, /实际执行 `doctor`/);
  assert.match(skill, /不能被当成成功/);
  assert.match(skill, /arcforge audit --root \./);
  assert.match(agentYaml, /\$arcforge-install/);
  assert.match(agentYaml, /display_name: "ArcForge Install"/);
  assert.doesNotMatch(agentYaml, /display_name: ".*[\u4e00-\u9fff].*"/);
  assert.match(agentYaml, /arcforge-skill-first/);
  assert.match(agentYaml, /--home\/--shim-dir/);
  assert.match(agentYaml, /--npm-cache/);
  assert.match(agentYaml, /临时 shim 目录排在 PATH 最前/);
  assert.match(agentYaml, /临时 HOME 外的不可修复 PATH shadow/);
  assert.match(agentYaml, /--verify/);
  assert.match(agentYaml, /--recommended-mode prompt/);
  assert.match(agentYaml, /--recommended-mode quick/);
  assert.match(agentYaml, /--recommended-mode governed/);
  assert.match(agentYaml, /--recommended-skills prompt/);
  assert.match(agentYaml, /不要生成旧式隐式快速安装命令/);
  assert.match(agentYaml, /快速安装模式/);
  assert.match(agentYaml, /严格治理模式/);
  assert.match(agentYaml, /https:\/\/github\.com\/feitianchengzi\/arckit/);
  assert.match(agentYaml, /https:\/\/github\.com\/feitianchengzi\/arckit-code/);
  assert.match(agentYaml, /AI Agent Skills 中心/);
  assert.match(agentYaml, /具体技术栈 coding skills 仓库/);
  assert.match(agentYaml, /SwiftUI\/Apple 客户端默认架构/);
  assert.match(agentYaml, /反馈平台接入流程/);
  assert.match(agentYaml, /AGENT ACTION REQUIRED: recommended install mode choice pending/);
  assert.match(agentYaml, /Recommended skill stage: pending_install_mode_choice/);
  assert.match(agentYaml, /最后一个 agent-facing action/);
  assert.match(agentYaml, /来源\/上游源/);
  assert.match(agentYaml, /关系记录归属 root/);
  assert.match(agentYaml, /飞天橙子内部使用者和开源使用者走同一个 GitHub-first 路径/);
  assert.match(agentYaml, /arcforge-desktop launcher/);
  assert.match(agentYaml, /不要使用 --update-path/);
  assert.match(agentYaml, /普通新终端可用/);
  assert.match(agentYaml, /node_modules vendor/);
  assert.match(agentYaml, /CLI shim 绝对路径验证 doctor 和 scan/);
  assert.match(agentYaml, /transient PATH warning/);
  assert.match(agentYaml, /PATH 命中是否指向当前安装/);
  assert.match(agentYaml, /实际执行 doctor/);
  assert.match(agentYaml, /自动覆盖修复/);
  assert.match(agentYaml, /安装必须失败/);

  assert.match(script, /skills\/arcforge-skill-first\/SKILL\.md/);
  assert.match(script, /installedSkillNames = \["arcforge", "arcforge-skill-first"\]/);
  assert.match(script, /recommendedSkillProjects/);
  assert.match(script, /parseRecommendedMode/);
  assert.match(script, /hasHelpFlag/);
  assert.match(script, /printHelp/);
  assert.match(script, /Print this help without installing/);
  assert.match(script, /Recommended Skill projects/);
  assert.match(script, /parseRecommendedSkillSelection/);
  assert.match(script, /--recommended-mode value/);
  assert.match(script, /--recommended-skills value/);
  assert.match(script, /Pass --recommended-mode quick or --recommended-mode governed when using --recommended-skills/);
  assert.match(script, /https:\/\/github\.com\/feitianchengzi\/arckit/);
  assert.match(script, /https:\/\/github\.com\/feitianchengzi\/arckit-code/);
  assert.match(script, /AI-agent-assisted software development skill center/);
  assert.match(script, /technology-stack-specific coding skill project/);
  assert.match(script, /SwiftUI\/Apple client architecture/);
  assert.match(script, /feedback platform integration/);
  assert.match(script, /installRecommendedSkillProjects/);
  assert.match(script, /printRecommendedModePrompt/);
  assert.match(script, /printRecommendedQuickSkillPrompt/);
  assert.match(script, /printRecommendedGovernancePrompt/);
  assert.match(script, /AGENT ACTION REQUIRED: recommended install mode choice pending/);
  assert.match(script, /Recommended skill stage: pending_install_mode_choice/);
  assert.match(script, /Recommended skill stage: pending_quick_skill_choice/);
  assert.match(script, /Recommended skill stage: pending_governance_endpoints/);
  assert.match(script, /Last agent-facing action/);
  assert.match(script, /Do not mark the install turn complete/);
  assert.match(script, /Do not finish with only a summary/);
  assert.match(script, /Ask this question in the final response/);
  assert.match(script, /你希望使用哪种模式/);
  assert.match(script, /关系记录归属 root/);
  assert.match(script, /"drift"/);
  assert.match(script, /"apply"/);
  assert.match(script, /"--confirm"/);
  assert.match(script, /"build:cli"/);
  assert.match(script, /"run", "build"/);
  assert.match(script, /"run", "package"/);
  assert.match(script, /installDesktopLauncher/);
  assert.match(script, /verifyInstall/);
  assert.match(script, /printVerifySummary/);
  assert.match(script, /npmCacheDir/);
  assert.match(script, /env\.npm_config_cache/);
  assert.match(script, /env\.HOME = installHome/);
  assert.match(script, /Electron launcher exists/);
  assert.match(script, /arcforge-desktop/);
  assert.match(script, /Desktop launcher/);
  assert.match(script, /"\.codex", "skills", skillName/);
  assert.match(script, /installHome/);
  assert.match(script, /explicitShimDir/);
  assert.match(script, /dryRun/);
  assert.match(script, /handleFatalError/);
  assert.match(script, /Stage: \$\{currentStage\}/);
  assert.match(script, /path\.join\(installHome/);
  assert.match(script, /updatePersistentPath/);
  assert.match(script, /repairPathCommandShadows/);
  assert.match(script, /addTransientShadowCheck/);
  assert.match(script, /firstDurableCommandPath/);
  assert.match(script, /first non-transient arcforge command resolves to this install/);
  assert.match(script, /first non-transient arcforge command runs doctor/);
  assert.match(script, /commandExitsSuccessfully/);
  assert.match(script, /first non-transient arcforge-desktop command resolves to this install/);
  assert.match(script, /Current agent shell may still resolve this first/);
  assert.match(script, /Cannot repair PATH shadowing command/);
  assert.match(script, /isTransientAgentShimDir/);
  assert.match(script, /codex-path/);
  assert.match(script, /\.local", "bin"/);
  assert.match(script, /optional: true/);
  assert.match(script, /Desktop command directory on PATH/);
  assert.doesNotMatch(script, /git push|gh pr|release upload/);
  assert.match(cliInstall, /isTransientAgentShimDir/);
  assert.match(cliInstall, /codex-path/);
  assert.match(cliInstall, /\.local", "bin"/);

  assert.match(readme, /从当前仓库安装 ArcForge/);
  assert.match(readme, /arcforge-skill-first/);
  assert.match(readme, /arckit-code/);
  assert.match(readme, /AI Agent Skills 中心/);
  assert.match(readme, /具体技术栈 coding skills 仓库/);
  assert.match(readme, /SwiftUI\/Apple 客户端默认架构/);
  assert.match(readme, /两个都装、只装其中一个或都不装/);
  assert.match(readme, /快速安装模式/);
  assert.match(readme, /严格治理模式/);
  assert.match(readme, /飞天橙子内部使用者和开源使用者走同一个 GitHub-first 安装路径/);
  assert.match(readme, /\[English\]\(docs\/en\/README\.md\)/);
  assert.match(readme, /skills\/arcforge-install/);
  assert.match(readme, /arcforge-desktop/);
  assert.match(enReadme, /Install ArcForge From This Repository/);
  assert.match(enReadme, /arcforge-skill-first/);
  assert.match(enReadme, /arckit-code/);
  assert.match(enReadme, /AI Agent Skills center/);
  assert.match(enReadme, /Technology-stack-specific coding workflows live elsewhere/);
  assert.match(enReadme, /SwiftUI\/Apple client architecture/);
  assert.match(enReadme, /install both, install only one, or skip both/);
  assert.match(enReadme, /Quick install mode/);
  assert.match(enReadme, /Governed mode/);
  assert.match(enReadme, /same GitHub-first installation path/);
  assert.match(enReadme, /\[简体中文\]\(\.\.\/\.\.\/README\.md\)/);
  assert.match(zhReadme, /从当前仓库安装 ArcForge/);
  assert.match(zhReadme, /arcforge-skill-first/);
  assert.match(zhReadme, /arckit-code/);
  assert.match(zhReadme, /AI Agent Skills 中心/);
  assert.match(zhReadme, /具体技术栈 coding skills 仓库/);
  assert.match(zhReadme, /两个都装、只装其中一个或都不装/);
  assert.match(zhReadme, /快速安装模式/);
  assert.match(zhReadme, /严格治理模式/);
  assert.match(zhReadme, /\[English\]\(\.\.\/en\/README\.md\)/);
  assert.match(zhReadme, /skills\/arcforge-install/);
  assert.match(zhReadme, /arcforge-desktop/);

  assert.match(arcforgeDesktopRouting, /arcforge-desktop/);
  assert.match(arcforgeDesktopRouting, /--root \/path\/to\/project --page destinations/);
  assert.match(arcforgeDesktopRouting, /页面级 context open/);
  assert.match(arcforgeCliOrchestration, /arcforge-desktop/);
});

test("arcforge install help guides recommended arckit choices", () => {
  const result = spawnSync(
    process.execPath,
    ["skills/arcforge-install/scripts/install-from-repo.mjs", "--help"],
    {
      cwd: new URL("..", import.meta.url),
      encoding: "utf8"
    }
  );

  assert.equal(result.status, 0, result.stderr);
  assert.match(result.stdout, /--recommended-mode <mode>/);
  assert.match(result.stdout, /Default: prompt\./);
  assert.match(result.stdout, /--recommended-mode quick/);
  assert.match(result.stdout, /--recommended-mode governed/);
  assert.match(result.stdout, /--recommended-skills all/);
  assert.match(result.stdout, /--recommended-skills arckit/);
  assert.match(result.stdout, /--recommended-skills arckit-code/);
  assert.match(result.stdout, /--recommended-skills skip/);
  assert.match(result.stdout, /https:\/\/github\.com\/feitianchengzi\/arckit/);
  assert.match(result.stdout, /https:\/\/github\.com\/feitianchengzi\/arckit-code/);
  assert.match(result.stdout, /AI-agent-assisted software development skill center/);
  assert.match(result.stdout, /technology-stack-specific coding skill project/);
});

test("arcforge install rejects old implicit recommended skill commands", () => {
  const result = spawnSync(
    process.execPath,
    ["skills/arcforge-install/scripts/install-from-repo.mjs", "--recommended-skills", "all", "--dry-run"],
    {
      cwd: new URL("..", import.meta.url),
      encoding: "utf8"
    }
  );

  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /Pass --recommended-mode quick or --recommended-mode governed/);
});
