import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { test } from "node:test";

test("arcforge skill first uses manual bridge validation only", async () => {
  const skill = await readFile(new URL("../skills/arcforge-skill-first/SKILL.md", import.meta.url), "utf8");
  const validation = await readFile(new URL("../skills/arcforge-skill-first/references/validation-execution.md", import.meta.url), "utf8");
  const checklist = await readFile(new URL("../skills/arcforge-skill-first/references/validation-checklist.md", import.meta.url), "utf8");
  const agentYaml = await readFile(new URL("../skills/arcforge-skill-first/agents/openai.yaml", import.meta.url), "utf8");

  assert.match(skill, /模拟测试/);
  assert.match(skill, /测一下这个 skill/);
  assert.match(skill, /让新 agent 模拟执行/);
  assert.match(skill, /验证默认只使用人工桥接隔离验证/);
  assert.match(skill, /不设计人工桥接失败、无法桥接、用户不愿桥接、平台不允许桥接、transcript 回放或受限 dry run 分支/);
  assert.match(skill, /不调用任何平台工具来替代人工桥接/);
  assert.match(skill, /不要把这类工具是否可用写进验证模式判断/);
  assert.match(skill, /人工桥接是主 agent 发起和指挥的验证执行手段/);
  assert.match(skill, /两段式桥接执行包/);
  assert.match(skill, /真实任务 prompt 必须像真实用户请求/);
  assert.match(skill, /第二段事后总结 prompt/);
  assert.match(skill, /awaiting_validation_transcript/);
  assert.match(skill, /不是完成状态/);
  assert.match(skill, /不能因为任务很小跳过验证发起或复测发起/);
  assert.doesNotMatch(skill, /自动隔离执行/);
  assert.doesNotMatch(skill, /sub-agent|runner|平台原生隔离/);

  assert.match(validation, /人工桥接隔离验证是唯一验证路径/);
  assert.match(validation, /不调用任何平台工具来替代人工桥接/);
  assert.match(validation, /不检查这类工具是否可用/);
  assert.match(validation, /不设计人工桥接失败、无法桥接、用户不愿桥接、平台不允许桥接、transcript 回放或受限 dry run 分支/);
  assert.match(validation, /主 agent 必须生成可复制的人工桥接执行包/);
  assert.match(validation, /先粘贴真实任务 prompt/);
  assert.match(validation, /再粘贴事后总结 prompt/);
  assert.match(validation, /第一段 prompt 只写真实用户会对 agent 说的话/);
  assert.match(validation, /禁止包含/);
  assert.match(validation, /“你是验证执行者”/);
  assert.match(validation, /交付执行包只表示进入 `awaiting_validation_transcript`/);
  assert.match(validation, /不表示验证完成/);
  assert.match(validation, /当前状态：`awaiting_validation_transcript`/);
  assert.match(validation, /直到用户回传执行记录/);
  assert.doesNotMatch(validation, /你是 Skill Validation Executor/);
  assert.doesNotMatch(validation, /自动隔离执行/);
  assert.doesNotMatch(validation, /sub-agent|runner|平台原生隔离/);
  assert.doesNotMatch(validation, /无法完成人工桥接|validation-mode: limited-current-session-dry-run|受限 Dry Run 记录|Transcript 回放记录/);

  assert.match(checklist, /没有调用平台工具替代人工桥接/);
  assert.match(checklist, /没有把“当前会话不能直接调用自动代理工具”写成未验证原因/);
  assert.match(checklist, /人工桥接执行包/);
  assert.match(checklist, /第一段真实任务 prompt/);
  assert.match(checklist, /第二段事后总结 prompt/);
  assert.match(checklist, /没有包含验证背景、诊断、观察重点、总结格式/);
  assert.match(checklist, /awaiting_validation_transcript/);
  assert.match(checklist, /没有把目标 skill 写成验证通过、闭环完成或可进入 ArcForge 治理交接/);
  assert.match(checklist, /完成或阻塞后执行第二段事后总结 prompt/);
  assert.doesNotMatch(checklist, /自动隔离执行/);
  assert.doesNotMatch(checklist, /sub-agent|runner|平台原生隔离/);

  assert.match(agentYaml, /唯一验证路径是人工桥接隔离验证/);
  assert.match(agentYaml, /用户在 skill、目标 skill 或 Skill First 上下文中只说“模拟测试”/);
  assert.match(agentYaml, /不要设计人工桥接失败、无法桥接、用户不愿桥接、平台不允许桥接、transcript 回放或受限 dry run 分支/);
  assert.match(agentYaml, /不要调用平台工具替代人工桥接/);
  assert.match(agentYaml, /不要把自动代理工具不可用作为未验证原因/);
  assert.match(agentYaml, /桥接执行包必须两段式/);
  assert.match(agentYaml, /第一段真实任务 prompt 只模拟真实用户请求/);
  assert.match(agentYaml, /第二段事后总结 prompt/);
  assert.match(agentYaml, /awaiting_validation_transcript/);
  assert.match(agentYaml, /不能写成验证通过、闭环完成或可进入治理交接/);
  assert.doesNotMatch(agentYaml, /Skill Validation Executor/);
  assert.doesNotMatch(agentYaml, /自动隔离执行/);
  assert.doesNotMatch(agentYaml, /sub-agent|runner|平台原生隔离/);
});
