import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { test } from "node:test";

test("arcforge install skill defines source install boundaries", async () => {
  const skill = await readFile(new URL("../skills/arcforge-install/SKILL.md", import.meta.url), "utf8");
  const agentYaml = await readFile(new URL("../skills/arcforge-install/agents/openai.yaml", import.meta.url), "utf8");
  const script = await readFile(new URL("../skills/arcforge-install/scripts/install-from-repo.mjs", import.meta.url), "utf8");
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const enReadme = await readFile(new URL("../docs/en/README.md", import.meta.url), "utf8");
  const zhReadme = await readFile(new URL("../docs/zh-CN/README.md", import.meta.url), "utf8");
  const arcforgeDesktopRouting = await readFile(new URL("../skills/arcforge/references/desktop-routing.md", import.meta.url), "utf8");
  const arcforgeCliOrchestration = await readFile(new URL("../skills/arcforge/references/cli-orchestration.md", import.meta.url), "utf8");
  const cliInstall = await readFile(new URL("../src/core/cli-install.ts", import.meta.url), "utf8");

  assert.match(skill, /name: arcforge-install/);
  assert.match(skill, /# ArcForge Install/);
  assert.match(skill, /skills\/arcforge/);
  assert.match(skill, /skills\/arcforge-skill-first/);
  assert.match(skill, /~\/\.codex\/skills\/arcforge/);
  assert.match(skill, /~\/\.codex\/skills\/arcforge-skill-first/);
  assert.match(skill, /arcforge-desktop/);
  assert.match(skill, /--desktop install/);
  assert.match(skill, /--desktop build/);
  assert.match(skill, /--desktop package/);
  assert.match(skill, /--update-path/);
  assert.match(skill, /--home/);
  assert.match(skill, /--shim-dir/);
  assert.match(skill, /--dry-run/);
  assert.match(skill, /--verify/);
  assert.match(skill, /--npm-cache/);
  assert.match(skill, /真实 `~\/\.npm`/);
  assert.match(skill, /Headless 验证/);
  assert.match(skill, /--skip-npm-install/);
  assert.match(skill, /npm run build:cli/);
  assert.match(skill, /写入当前仓库的 `dist\/`/);
  assert.match(skill, /写入 `dist-ui\/`/);
  assert.match(skill, /不要把这个安装流程描述成 marketplace/);
  assert.match(skill, /持久 PATH/);
  assert.match(skill, /agent 注入的临时 PATH/);
  assert.match(skill, /command -v arcforge-desktop/);
  assert.match(skill, /<CLI shim path> doctor/);
  assert.match(skill, /<CLI shim path> scan --root \./);
  assert.match(skill, /当前会话 PATH 噪声/);
  assert.match(skill, /PATH shadow/);
  assert.match(skill, /必须修复可修复的 PATH shadow/);
  assert.match(skill, /首个非临时 `arcforge`/);
  assert.match(skill, /实际执行 `doctor`/);
  assert.match(skill, /不能被当成成功/);
  assert.match(skill, /arcforge audit --root \./);
  assert.match(agentYaml, /\$arcforge-install/);
  assert.match(agentYaml, /display_name: "ArcForge Install"/);
  assert.doesNotMatch(agentYaml, /display_name: ".*[\u4e00-\u9fff].*"/);
  assert.match(agentYaml, /arcforge-skill-first/);
  assert.match(agentYaml, /--home\/--shim-dir/);
  assert.match(agentYaml, /--npm-cache/);
  assert.match(agentYaml, /--verify/);
  assert.match(agentYaml, /arcforge-desktop launcher/);
  assert.match(agentYaml, /不要使用 --update-path/);
  assert.match(agentYaml, /普通新终端可用/);
  assert.match(agentYaml, /node_modules vendor/);
  assert.match(agentYaml, /CLI shim 绝对路径验证 doctor 和 scan/);
  assert.match(agentYaml, /transient PATH warning/);
  assert.match(agentYaml, /PATH 命中是否指向当前安装/);
  assert.match(agentYaml, /实际执行 doctor/);
  assert.match(agentYaml, /自动覆盖修复/);
  assert.match(agentYaml, /安装必须失败/);

  assert.match(script, /skills\/arcforge-skill-first\/SKILL\.md/);
  assert.match(script, /installedSkillNames = \["arcforge", "arcforge-skill-first"\]/);
  assert.match(script, /"build:cli"/);
  assert.match(script, /"run", "build"/);
  assert.match(script, /"run", "package"/);
  assert.match(script, /installDesktopLauncher/);
  assert.match(script, /verifyInstall/);
  assert.match(script, /printVerifySummary/);
  assert.match(script, /npmCacheDir/);
  assert.match(script, /env\.npm_config_cache/);
  assert.match(script, /env\.HOME = installHome/);
  assert.match(script, /Electron launcher exists/);
  assert.match(script, /arcforge-desktop/);
  assert.match(script, /Desktop launcher/);
  assert.match(script, /"\.codex", "skills", skillName/);
  assert.match(script, /installHome/);
  assert.match(script, /explicitShimDir/);
  assert.match(script, /dryRun/);
  assert.match(script, /handleFatalError/);
  assert.match(script, /Stage: \$\{currentStage\}/);
  assert.match(script, /path\.join\(installHome/);
  assert.match(script, /updatePersistentPath/);
  assert.match(script, /repairPathCommandShadows/);
  assert.match(script, /addTransientShadowCheck/);
  assert.match(script, /firstDurableCommandPath/);
  assert.match(script, /first non-transient arcforge command resolves to this install/);
  assert.match(script, /first non-transient arcforge command runs doctor/);
  assert.match(script, /commandExitsSuccessfully/);
  assert.match(script, /first non-transient arcforge-desktop command resolves to this install/);
  assert.match(script, /Current agent shell may still resolve this first/);
  assert.match(script, /Cannot repair PATH shadowing command/);
  assert.match(script, /isTransientAgentShimDir/);
  assert.match(script, /codex-path/);
  assert.match(script, /\.local", "bin"/);
  assert.match(script, /optional: true/);
  assert.match(script, /Desktop command directory on PATH/);
  assert.doesNotMatch(script, /git push|gh pr|release upload/);
  assert.match(cliInstall, /isTransientAgentShimDir/);
  assert.match(cliInstall, /codex-path/);
  assert.match(cliInstall, /\.local", "bin"/);

  assert.match(readme, /从当前仓库安装 ArcForge/);
  assert.match(readme, /arcforge-skill-first/);
  assert.match(readme, /\[English\]\(docs\/en\/README\.md\)/);
  assert.match(readme, /skills\/arcforge-install/);
  assert.match(readme, /arcforge-desktop/);
  assert.match(enReadme, /Install ArcForge From This Repository/);
  assert.match(enReadme, /arcforge-skill-first/);
  assert.match(enReadme, /\[简体中文\]\(\.\.\/\.\.\/README\.md\)/);
  assert.match(zhReadme, /从当前仓库安装 ArcForge/);
  assert.match(zhReadme, /arcforge-skill-first/);
  assert.match(zhReadme, /\[English\]\(\.\.\/en\/README\.md\)/);
  assert.match(zhReadme, /skills\/arcforge-install/);
  assert.match(zhReadme, /arcforge-desktop/);

  assert.match(arcforgeDesktopRouting, /arcforge-desktop/);
  assert.match(arcforgeDesktopRouting, /--root \/path\/to\/project --page destinations/);
  assert.match(arcforgeDesktopRouting, /页面级 context open/);
  assert.match(arcforgeCliOrchestration, /arcforge-desktop/);
});
